services:
  thrify:
    build:
      context: .
      target: development
    ports: 
      - "5173:5173"
    volumes: 
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true